const data = {
  products: [
    {
      _id: '1',
      name: '#f Torsepan hang Drum',
      category: 'Hang Drum',
      image: '/images/product-1.jpg',
      price: 1200,
      brand: 'Torsepan',
      rating: 4.5,
      numReviews: 10,
      description: 'One of best Hang Drum manufactures product',
    },
    {
      _id: '2',
      name: 'Pygmy Torsepan hang Drum',
      category: 'Hang Drum',
      image: '/images/product-2.jpg',
      price: 1400,
      brand: 'Torsepan',
      rating: 5,
      numReviews: 16,
      description: 'One of best Hang Drum manufactures product',
    },
    {
      _id: '3',
      name: 'D# Torsepan hang Drum',
      category: 'Hang Drum',
      image: '/images/product-3.jpg',
      price: 1100,
      brand: 'Torsepan',
      rating: 4,
      numReviews: 4,
      description: 'One of best Hang Drum manufactures product',
    },
    {
      _id: '4',
      name: '#f Torsepan hang Drum',
      category: 'Hang Drum',
      image: '/images/product-4.jpg',
      price: 1300,
      brand: 'Torsepan',
      rating: 4.5,
      numReviews: 10,
      description: 'One of best Hang Drum manufactures product',
    },
    {
      _id: '5',
      name: '#f Torsepan hang Drum X',
      category: 'Hang Drum',
      image: '/images/product-5.jpg',
      price: 1200,
      brand: 'Torsepan',
      rating: 5,
      numReviews: 7,
      description: 'One of best Hang Drum manufactures product',
    },
    {
      _id: '6',
      name: 'Torsepan hang Drum ZX',
      category: 'Hang Drum',
      image: '/images/product-6.jpg',
      price: 1200,
      brand: 'Torsepan',
      rating: 4.5,
      numReviews: 3,
      description: 'One of best Hang Drum manufactures product',
    },
  ],
};
export default data;
